# Generated by Django 3.2.5 on 2021-07-28 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('image', models.TextField(verbose_name='Ссылка на картинку продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('active', models.BooleanField(default=True, verbose_name='Продукт активен ?')),
                ('working_time', models.CharField(max_length=50, verbose_name='Режим работы')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Условия скидки')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Счетчик просмотров')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название соц сети')),
                ('image', models.TextField(verbose_name='Ссылка на картинку социальной сети')),
                ('link', models.TextField(verbose_name='Ссылка для перехода в текущую соц сеть')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.term'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('type', models.CharField(max_length=20, verbose_name='Whatsapp or Telegram')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Процент скидки')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discount_app.product')),
            ],
        ),
    ]
