# Generated by Django 3.2.5 on 2021-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0002_auto_20210805_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Кастомный порядковый номер'),
        ),
    ]
