# Generated by Django 3.2.5 on 2021-08-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_app', '0003_discount_order_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discounts',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='users',
            new_name='user',
        ),
    ]
